### ISSUE TITLE
Come up with some improvement ideas and talk to teammate

### ISSUE THREAD

**Issue by Pacy-Wu** [francesevachang/Lemme-Shoyu#3]
Assignee:
@francesevachang 

Requirement: 
1. Drop down some bullet points
2. Create tasks

**Comment by Pacy-Wu** [comment]
Some ideas we have right now, 

- Cross-platform development for Android and iOS
- AI on image 
- Dynamic database
- change api??
- change theme
- detect expiration date
- plant a tree when eat healthy / prep meal
- pop up notification when food expires

**Comment by francesevachang** [comment]
- [function] shows pop up notification when a food expires
- [function] detects the expiration date on packing through the camera
- [function] recommends name of food/ingredient when scanned (AI on image)
- [function] allows user to change themes
- [function] allows user to add recipe (dynamic database) (or find a better API)
- Cross-platform development for Android and iOS
- [function] lets user to plant a tree every time they eat healthy / prep meal (or some other reward mechanism)

**Comment by Pacy-Wu** [comment]
Looks good to me!
